features/evaluation.feature

- updates `Resolves based on context` and `Type error` scenarios, removing redundant "then" after the start of "Then" statement
Fixes #10

fix: redundant "then" usage in evaluation.feature

---

Dockerfile
features/caching.feature
features/evaluation.feature
testing-flags.json

Assert that providers are being selective in their purging of cache.
Fixes #19

feat!: amend caching scenarios to check that cache is not just being purged

---

renovate.json

Adds renovate config to monitor FLAGD_VERSION in Dockerfile
Fixes #16

chore: renovate regex manager to monitor FLAGD_VERSION in Dockerfile

---

features/caching.feature

- Increase sleep in caching tests from 50ms to 100ms
The tests switching to symbolic links has created longer delays.

feat: increase sleep in caching tests from 50ms to 100ms

---

features/caching.feature

- increase sleep in caching tests from 250ms to 1000ms

feat: increase sleep in caching tests from 250ms to 1000ms

---

.gherkin-lintrc
README.md
flagd/Dockerfile
flags/custom-ops.json
flags/evaluator-refs.json
flags/testing-flags.json
flags/zero-flags.json
gherkin/flagd-json-evaluator.feature
gherkin/flagd.feature
sync/Dockerfile

adds test suite (and containers) with.
`flagd.feature` includes tests relevant to flagd and all flagd providers:
* default value (zero-value) handling (some proto3 implementations handle these inconsistently).
* basic event handling
`flagd-json-evaluator.feature` includes tests relevant to flagd and in-process providers:
* custom JSONLogic operators (`starts_with`, `ends_with`, `fractional`, `sem_ver`)
* evaluator reuse via `$ref`
---
If you want, you can manually test some of this by calling flagd or the sync server from console once you build the containers
flagd: 
```shell
curl -X POST "http://localhost:8013/schema.v1.Service/ResolveString"       -d '{"flagKey":"fractional-flag","context":{"user":{"name":"ace"}}}' -H "Content-Type: application/json"
// …
```

feat: flagd gherkin suite and flags

---

gherkin/flagd-json-evaluator.feature

* some cucumber implementations need the example matrix values to be quoted
* fixed some incorrect default values to match flag configs

fix: various gherkin fixes

---

sync/pkg/server.go

* adds `$evaluators` to sync payload (was not implemented).

feat: add evaluator support in sync

---

flagd/Dockerfile
flagd/Dockerfile.unstable
flags/custom-ops.json
flags/edge-case-flags.json
flags/error-flags.json
flags/testing-flags.json
gherkin/flagd-json-evaluator.feature
sync/Dockerfile

This PR adds tests for a few flagd configuration edge-cases:
- targeting rule returns `null` should fall through to `defaultVariant` and return reason `DEFAULT`
- invalid/erroneous JSON logic (should error, and cause use of application (SDK) default)
- targeting returns a variant which is not in variant definition (should error, and cause use of application (SDK)  default)
- invalid sem_ver, fractional, and string-cmp inputs (should return null/false)
- non-string variants returned from the targeting rule
- timestamps
Fixes: https://github.com/open-feature/flagd-testbed/issues/84
Fixes: https://github.com/open-feature/flagd-testbed/issues/74
Relates to: https://github.com/open-feature/flagd/pull/1041

feat: add tests for config edge cases

---

flags/edge-case-flags.json
gherkin/flagd-json-evaluator.feature

- adds empty context test
- fixed typos in Gherkin test definition

feat: add empty context test

---

flags/testing-flags.json
gherkin/flagd-json-evaluator.feature
gherkin/flagd-reconnect.feature

Small test for consistency of all flagd providers regarding startup errors.
This works in the java contribs once https://github.com/open-feature/java-sdk/pull/794 is merged.
It should eventually be implemented everywhere.

feat: provider unavailable, targeting key tests

---

sync/pkg/server.go

Flagd e2e tests were failing since v1.KeyValue does not exist anymore

fix: update server.go to use new metadata struct

---

flags/custom-ops.json
gherkin/flagd-json-evaluator.feature

Adds a new fractional test and assertions. These don't require any new test implementation in consumers since they use existing clauses/bindings.
The new flag tests:
- new, non-percentage weighting
- defaulting to `1` if no weight is passed
- default bucketing based on targeting key
I tested this locally with Java and it passes both RPC and in-process.

feat: fractional non-percentage and shorthand

---

gherkin/flagd-json-evaluator.feature

When I first wrote these assertions, I had incorrectly setup the cuke bindings in the JS repo where I tested it; I was setting the targeting key to `"jon@company.com"` (including the quotes!!!) which obviously resulted in a different assignment. Then when I started implementing these tests in other repos, nothing worked :sweat_smile: 
These are the actual correct responses, which you can test in flagd:
```shell
curl -X POST "http://localhost:8013/flagd.evaluation.v1.Service/ResolveString"       -d '{"flagKey":"fractional-flag-shorthand","context":{"targetingKey":"jane@company.com"}}' -H "Content-Type: application/json"
// {"value":"tails","reason":"TARGETING_MATCH","variant":"tails","metadata":{}}
```
```shell
curl -X POST "http://localhost:8013/flagd.evaluation.v1.Service/ResolveString" …
```

fix: correct assertions for shorthand targeting

---

gherkin/config.feature

I tested this with Java and Python.
With Tags we can deactivate features.
This files is not suppose to be run in an e2e env, but as a unittest for the configuration generation
Questions:
- is java our correct implemenation? naming and type wise (why is keep alive in java a long, and everything else is a int)
java code for the whole gherkin file:
```java
package dev.openfeature.contrib.providers.flagd.e2e.steps.config;
import dev.openfeature.contrib.providers.flagd.Config;
import dev.openfeature.contrib.providers.flagd.FlagdOptions;
import dev.openfeature.contrib.providers.flagd.resolver.grpc.cache.CacheType;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Arrays;
import …
```

feat: add Gherking file for config

---

gherkin/flagd-rpc-caching.feature

This adds another gherkin file for cache evaluation in RPC mode.

feat: Gherkin file for caching evaluation

---

gherkin/config.feature

The initial version of the gherkin file had some issues. It was not written in passive voice, and there have been no given states.
Furthermore, it missed important fields from the flagd spec.
https://flagd.dev/reference/specifications/providers/#configuration-options

feat: rework config gherkin file

---

flags/metadata-flags.json
gherkin/targeting.feature
launchpad/configs/default.json
launchpad/configs/ssl.json

With this pullrequest our flagd-testbed will provide flagd context values (`--context-value` cli option) and a gherkin test to ensure these context values are used during flag evaluation.

feat: Context value hydration via flagd

---

flags/metadata-flags.json
launchpad/configs/default.json
launchpad/configs/ssl.json

viper is not honoring case sensitivity on messages, hence the current configuration will not work. This pr fixes this.

fix: Casesensitive messages for context hydration.

---

gherkin/targeting.feature

Adds a test for asserting the injected context still works after connection error/stale events.

feat: add context-sensitive test with connection err

---

gherkin/contextEnrichment.feature
gherkin/targeting.feature

Add more testcases for context enrichment
blocks: https://github.com/open-feature/java-sdk-contrib/pull/1230
blocks: https://github.com/open-feature/python-sdk-contrib/pull/195

feat: improve contextEnrichment to handle special cases.

---

flagd/Dockerfile
launchpad/.gitignore
launchpad/handlers/http.go
launchpad/main.go
launchpad/pkg/filewatcher.go
launchpad/pkg/flagd.go
launchpad/pkg/json.go
launchpad/pkg/json_test.go

closes: https://github.com/open-feature/flagd-testbed/issues/222

feat: listening for logs before returning a http status code

---

flags/zero-flags.json
gherkin/evaluation.feature

As discovered within https://github.com/open-feature/python-sdk-contrib/issues/213 we do not have testcases covering zero values and targeting.
This pull request extends our zero value tests with some targeted rules, and helps us to detect this issues earlier.
relates: https://github.com/open-feature/python-sdk-contrib/issues/213

feat: Add testcases for targeted zero values

---

flags/selector-flag-combined-metadata.json
flags/selector-flag-set-metadata.json
gherkin/metadata.feature

Makes the flag keys of feature flags unique to work around a selector issue where the last flag with a key overwrites all other flags with the same key, even when using different selectors (https://github.com/open-feature/flagd/issues/1596)
Workaround for https://github.com/open-feature/flagd/issues/1596 to fix https://github.com/open-feature/python-sdk-contrib/issues/119

fix: make flag keys unique as a workaround for selector issue

---

gherkin/connection.feature
launchpad/handlers/http.go
launchpad/pkg/filewatcher.go
launchpad/pkg/flagd.go

Reintroduces the code to change a feature flag when the change endpoint is called. Increases test stability.

fix: reintroduce change flag request and increase test stability

---

launchpad/pkg/filewatcher.go
launchpad/pkg/flagd.go

Removes the combined flags file on restart command. This emulates an unavailable file for the file mode

fix: Remove combined flags file on restart

---

gherkin/rpc-caching.feature

Within certain implementations, we just use a mapper to convert this JSON property, e.g. Java. But this will be mapped to an integer rather than a double, invalidating our comparison checks.
This is a quick fix to make our builds pass again.
see: https://github.com/open-feature/java-sdk-contrib/issues/1307

fix: change object return value to double

---

flags/testing-flags.json
gherkin/evaluation.feature

Adds tests for optional `defaultVariant` to the suite. I've tested this locally with my implementation of the no-defaultVariant-support in JS, and it works as expected.
The 3 flags and 6 assertions I've added test:
- `defaultValue: null` with no `targeting` -> code default (`true` and `false`), FLAG_NOT_FOUND
- `defaultValue: undefined` with no `targeting` -> code default (string1 vs string2), FLAG_NOT_FOUND
- `defaultValue: undefined` with targeting that matches -> TARGETING_MATCH
- `defaultValue: undefined` with targeting that does not match -> code default (int), FLAG_NOT_FOUND
Resolves: https://github.com/open-feature/flagd-testbed/issues/268

feat: add tests for no defaultVariant

---

gherkin/sync-payload.feature
launchpad/configs/sync-payload.json

- adds tests for the disable-sync-metadata toggle in flagd. The tests check that with the endpoint disabled, flags are still evaluated correctly.
[#1584](https://github.com/open-feature/flagd/issues/1584)

feat: Add tests for temporary metadata toggle
